# Site settings
author: Alex Lau
title: Bits on Bits on Bits
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bitsonbitsonbits.com" # the base hostname & protocol for your site
twitter_username: mralexlau
github_username:  mralexlau

# Build settings
markdown: kramdown

gems: [octopress-codefence, octopress-genesis-theme]

disqus_short_name: bitsonbitsonbits
disqus_show_comment_count: false
